analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    library_private_types_in_public_api: ignore
    invalid_use_of_protected_member: ignore

include: package:very_good_analysis/analysis_options.yaml