name: testinaya
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  auto_route: ^9.2.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  slang: ^3.31.2
  slang_flutter: ^3.31.0
  uuid: ^4.5.0
  very_good_analysis: ^6.0.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  slang_build_runner: ^3.31.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/button_icons/
    - assets/icons/facilities/
    - assets/icons/house_types/
    - assets/icons/sleep_places/
    - assets/images/funs/
    - assets/images/avatars/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/sf_pro_display_regular.otf
    - family:  ButtonIcons
      fonts:
        - asset: assets/fonts/ButtonIcons.ttf

